# Generated by Django 4.2.6 on 2023-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0010_person_groupe_alter_person_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="group",
            field=models.CharField(
                choices=[("s", "s"), ("p", "p"), ("t", "i"), ("Ext", "Ext")],
                default="-",
                max_length=3,
            ),
        ),
    ]
