# Generated by Django 4.2.6 on 2023-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0011_course_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="group",
            field=models.CharField(
                choices=[("s", "s"), ("p", "p"), ("t", "i"), ("i", "i")],
                default="-",
                max_length=3,
            ),
        ),
    ]
