# Generated by Django 4.2.6 on 2023-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0013_alter_course_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("O1", "O1"),
                    ("O2", "O2"),
                    ("FE", "FE"),
                    ("FP", "FP"),
                    ("MS", "MS"),
                    ("PH", "PH"),
                    ("-", "-"),
                ],
                default="-",
                max_length=3,
            ),
        ),
    ]
